// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkBcFmxuUGfoxhIZXQbK6evfRfGKk58o4',
    appId: '1:139103647006:web:3a0732363660d8061a850f',
    messagingSenderId: '139103647006',
    projectId: 'fir-chat-app-2e3e7',
    authDomain: 'fir-chat-app-2e3e7.firebaseapp.com',
    storageBucket: 'fir-chat-app-2e3e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4SlsvHOaYFIwqIpVLj7kafOwjU3rgTtM',
    appId: '1:139103647006:android:62019d5e86ecedf01a850f',
    messagingSenderId: '139103647006',
    projectId: 'fir-chat-app-2e3e7',
    storageBucket: 'fir-chat-app-2e3e7.firebasestorage.app',
    androidClientId:
        '139103647006-g96mpkk7g229ef3lq8cpc14e150mk4er.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnMBkfJB3mJw8KHNxQllqmR8jjzAyRxk',
    appId: '1:139103647006:ios:e8bd78a7799c944c1a850f',
    messagingSenderId: '139103647006',
    projectId: 'fir-chat-app-2e3e7',
    storageBucket: 'fir-chat-app-2e3e7.firebasestorage.app',
    androidClientId:
        '139103647006-g96mpkk7g229ef3lq8cpc14e150mk4er.apps.googleusercontent.com',
    iosClientId:
        '139103647006-gihvko2qi25ict4n65t9fr6sulqilbd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFnMBkfJB3mJw8KHNxQllqmR8jjzAyRxk',
    appId: '1:139103647006:ios:e8bd78a7799c944c1a850f',
    messagingSenderId: '139103647006',
    projectId: 'fir-chat-app-2e3e7',
    storageBucket: 'fir-chat-app-2e3e7.firebasestorage.app',
    androidClientId:
        '139103647006-g96mpkk7g229ef3lq8cpc14e150mk4er.apps.googleusercontent.com',
    iosClientId:
        '139103647006-gihvko2qi25ict4n65t9fr6sulqilbd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkBcFmxuUGfoxhIZXQbK6evfRfGKk58o4',
    appId: '1:139103647006:web:ef5b9c93a0601df01a850f',
    messagingSenderId: '139103647006',
    projectId: 'fir-chat-app-2e3e7',
    authDomain: 'fir-chat-app-2e3e7.firebaseapp.com',
    storageBucket: 'fir-chat-app-2e3e7.firebasestorage.app',
  );
}
